version: 2

project_name: bunny

before:
  hooks:
    - go mod tidy

builds:
  - id: bunny
    main: ./cmd/bunny
    binary: bunny
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: bunny
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: ["tar.gz"]
    files:
      - README.md
      - CHANGELOG.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  use: github
  format: "{{ .SHA }}: {{ .Message }}{{ if .Logins }} ({{ .Logins | englishJoin }}){{ end }}"
  filters:
    exclude:
      - '^docs(\(.+\))?:'
      - '^test(\(.+\))?:'
      - '^chore(\(.+\))?:'
      - '^ci(\(.+\))?:'
      - '^refactor(\(.+\))?:'
      - '^build(\(.+\))?:'
      - '^Init$'
      - 'Merge pull request'
      - 'Merge branch'
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1

release:
  prerelease: auto
